### ISSUE TITLE
cordova-plugin-estimote/EstimoteBeacons.m:2:9: fatal error:

### ISSUE THREAD

**Issue by mydevpartner** [evothings/phonegap-estimotebeacons#116]
Since I updated my xcode to 7.3.1 I am now no longer able to compile my app on iOS. I am getting :

EstimoteBeacons.m:2:9: fatal error: 'EstimoteSDK/ESTUtilityManager.h' file not found
1>  #import <EstimoteSDK/ESTUtilityManager.h>
1>          ^
1>  1 error generated.
1>
1>  ** BUILD FAILED **

Any thoughts?

Sylvain Audet
MyDevPartner.com

**Comment by 0NDR** [comment]
I fixed this by renaming EstimoteSDK.framework/Versions/A to EstimoteSDK.framework/Versions/Current , not exactly sure why that fixed it.

**Comment by chy600** [comment]
I got it working by moving the Headers folder and EstimoteSDK executable file that are under EstimoteSDK.framework/Versions/A to EstimoteSDK.framework/.
