### ISSUE TITLE
How to keep plugin from loading on non iOS 7 devices?

### ISSUE THREAD

**Issue by samrung** [evothings/phonegap-estimotebeacons#25]
Thanks for the great plugin. I've got it working in Cordova 3.3 in 7.0 and 7.1.

However, the app I'm building is targeted for iOS 5.1 and above (iBeacons are not central to the overall app). Any attempt to run the app on anything less than 7 results in a fatal error on startup:

dyld: Symbol not found: _OBJC_CLASS_$_CLBeaconRegion

Obviously, iBeacons aren't supported in anything less than 7.0, but do you know of a way to conditionally load the plugin? I have code in onDeviceReady handlers to detect iOS version and not execute any of the iBeacon code, but it fails before it even gets to any of my code.
